### ISSUE TITLE
MacOS Install

### ISSUE THREAD

**Issue by snoolord** [nakano000/Resolve_Script#2]
I'm not familiar with python but would love to use this project on mac. 
What operations does the .exe file perform?

**Comment by nakano000** [comment]
Inside the unzipped folder, the exe will run the following commands:
`python3 bin/launcher.py`

I haven't tried it on a mac, but it may work if you set up python.
`pin3 install -r requirements.txt`

**Comment by Yur0w** [comment]
Did you have any luck with this? I would love to use this script on mac too.

**Comment by Yur0w** [comment]
> I'm not familiar with python but would love to use this project on mac. What operations does the .exe file perform?

I'll try to get it to work. l'll let you know if I have any luck :)

**Comment by GeisterKiller** [comment]
> > I'm not familiar with python but would love to use this project on mac. What operations does the .exe file perform?
> 
> I'll try to get it to work. l'll let you know if I have any luck :)

did you make it?

**Comment by quangmng** [comment]
+1, Will try that on my mac as well. Really love the Subtitles2Txt+ one. 
てきとさん、ランチャーのmacOS版を作ってください。Windows版の「Subtitles2Text+」スクリプトがとても気に入っていて、Macでも使いたいのです。

**Comment by nakano000** [comment]
> +1, Will try that on my mac as well. Really love the Subtitles2Txt+ one. てきとさん、ランチャーのmacOS版を作ってください。Windows版の「Subtitles2Text+」スクリプトがとても気に入っていて、Macでも使いたいのです。

残念ながら、私はmacを持っていないので、作ることが出来ません。

**Comment by nakano000** [comment]
> and is there a possibility to install the whole thing manually?

I don't have a mac, so I don't know anything about mac.

**Comment by GeisterKiller** [comment]
> > and is there a possibility to install the whole thing manually?
> 
> I don't have a mac, so I don't know anything about mac.

Ok. Let me know if you find a solution.

**Comment by Yur0w** [comment]
> 

No sorry, not yet :(

**Comment by quangmng** [comment]
Update: I followed the Linux instructions outlined in the readme & installing the dependencies from the "requirements.txt" file. Turns out I have an M1 Mac & these dependencies didn't play nicely with it :( 
----
readme.mdに記載されているLinuxの説明に従い、requirements.txtファイルから依存関係をインストールした。結局、私はM1のMacを持っていて、これらの依存関係はうまく動作しないことがわかった。:(
----
<img width="1002" alt="Screenshot 2023-08-05 at 18 13 33" src="https://github.com/nakano000/Resolve_Script/assets/57740309/873769ab-d1e1-418a-ab6e-fb40c6dae178">
<img width="1002" alt="Screenshot 2023-08-05 at 18 07 28" src="https://github.com/nakano000/Resolve_Script/assets/57740309/b748983d-40bd-4633-ab69-ad82d9a4b947">
-----
So I'm facing a dilemma of either changing every code that involves PySide 2 -> PySide 6 (which I highly doubt will work) or somehow running them thru Wine (Windows emulation) 
-----
そのため、PySide 2を含むすべてのコードをPySide 6に変更するか（うまくいくかどうかは大いに疑問だが）、どうにかしてWine（Windowsエミュレーション）を通して実行するかというジレンマに直面している。

**Comment by nakano000** [comment]
pyside2が問題なのですね。
ちょっと時間がかかりますが、将来的にpyside6を使うように変更します。

**Comment by quangmng** [comment]
Thank you so much! I'm looking forward to your next updates 😄 

I'm still quite new to Python, so I don't know much about how GUI libraries work and such. I changed the PySide2 to 6 on my own, but some function calls were unsuccessful due to missing modules while importing them. I hope you can find some leads regarding that and update us. Can't wait to see this in action!
--//--
本当にありがとう！次回の更新も楽しみにしています。😄

Pythonはまだ初心者なので、GUIライブラリの仕組みとかよくわかりません。自力でPySide2をPySide6に変更したのですが、インポート中にモジュールが足りず、関数呼び出しが失敗することがありました。それに関して何か手がかりを見つけて、みんなに最新情報を教えてくれるといいんだけど。これが動くのを見るのが待ち遠しいです！

**Comment by nakano000** [comment]
Macに仮対応したので、閉じます。

**Comment by quangmng** [comment]
Yep, the Mac version works now. The only thing it needs is Subtitles2Text+ script :). 
うん、Mac版も動くようになった。必要なのはSubtitles2Text+スクリプトだけだ。
----
<img width="1652" alt="Screenshot 2023-09-17 at 10 22 15" src="https://github.com/nakano000/Resolve_Script/assets/57740309/68aee13c-fa35-4926-acf7-ca45ee691323">
Thank you so much! - ありがとうございます！
----
Also, should I create another GitHub issue regarding that script?
また、そのスクリプトに関して、別のGitHub issueを作成すべきでしょうか？

**Comment by quangmng** [comment]
PS.: the .command file did not execute properly to launch GUI.
GUIを起動するための.commandファイルが正しく実行されなかった。
<img width="1002" alt="Screenshot 2023-09-17 at 10 51 58" src="https://github.com/nakano000/Resolve_Script/assets/57740309/63f73ff6-cb0b-452f-951c-4e1663fe5969">
Solved by opening launcher.py from terminal with "python3 bin/launcher.py"
ターミナルから "python3 bin/launcher.py "でlauncher.pyを開くことで解決しました。

**Comment by nakano000** [comment]
新しいバージョンをアップロードしました。

・pythonをインストール
・setup_python.commandを実行
・りぞりぷと.commandを実行

で動くと思います。

また、まだ問題があるようなら別のGitHub issueを作ってください。
